# Generated by Django 5.1.2 on 2024-10-24 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penaltyball',
            old_name='penalty_owner',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='penaltyball',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 24, 17, 22, 44, 883866), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 24, 17, 22, 44, 882866), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 24, 17, 22, 44, 882866), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
